services:
 ####################### App #######################
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go_modules:/go/pkg/mod
    ports:
      - "${APP_PORT:-5050}:5050"
    environment:
      APP_ENV: docker
    depends_on:
      - postgres
      - redis
    networks:
      - app_net
    restart: unless-stopped

 ####################### ELK #######################
  setup:
    build:
      context: docker/elk/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./docker/elk/setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./docker/elk/setup/helpers.sh:/helpers.sh:ro,Z
      - ./docker/elk/setup/roles:/roles:ro,Z
      - setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
    networks:
      - app_net
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: docker/elk/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: elasticsearch
    volumes:
      - ./docker/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT:-9300}:9300"
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - app_net
    restart: unless-stopped

  kibana:
    build:
      context: docker/elk/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./docker/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      - elasticsearch:/usr/share/kibana/data:Z
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - app_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    build:
      context: docker/elk/filebeat/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
      #- ../prod/logs:/var/log/filebeat/service:ro
      - ./docker/elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log/filebeat/service:ro
      - logs:/var/log/filebeat
      - logs:/app:ro

    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
    networks:
      - app_net
    depends_on:
      - elasticsearch
  postgres:
    image: postgres:latest
    container_name: postgres_con
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-golang_web_api}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    networks:
      - app_net
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_con
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@main.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-secret}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-8589}:80"
    networks:
      - app_net
    restart: unless-stopped
    depends_on:
      - postgres
  redis: 
    image: redis:latest
    container_name: redis_con
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "${REDIS_PORT:-6385}:6379"
    networks:
      - app_net
    restart: unless-stopped











volumes:
  postgres:
  pgadmin:
  redis:
  logs:
  setup:
  elasticsearch:
  prometheus_data:
  go_modules:
networks:
  app_net:
    driver: bridge
