ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM mirror2.chabokan.net/elasticsearch:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
