App:
  Env: "local"
  Name: "Test"
  Lang: "fa"
  Broker: "nats"
Server:
  Port: 5050
  RunMode: debug
Logger:
  FileName: ../logs/app.log
  Encoding: json
  Level: debug
  Logger: zerolog
Cors:
  AllowOrigins: "*"
Postgres:
  Host: postgres_con
  Port: 5432
  User: postgres
  Password: secret
  DB: golang_web_api
  SslMode: disable
  TimeZone: Asia/Tehran
Redis:
  Host: redis_con
  Port: 6379
  Password: password
  DB: 0
  DialTimeout: 5
  ReadTimeout: 5
  WriteTimeout: 5
  PoolSize: 10
  PoolTimeout: 15
  IdleCheckFrequency: 500
  IdleTimeout: 500
JWT:
  Secret: "secret"
  RefreshSecret: "refresh_secret"
  AccessTokenExpireDuration: 3600
  RefreshTokenExpireDuration: 36000
Nats:
  Host: nats_con
  Port: 4222
  Password: secret
  JetStream:
    Enabled: true
